### ISSUE TITLE
Most recent pkg is looping and not completing the update

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/rxOS#118]
rxos-v1.1-201607161733+c97bd1a-full

When I insert a flash drive with this pkg, the process never completes. I've waited over 10 minutes. Previous updates completed in less than 5 minutes. When I remove the flash drive, the CHIP is bricked.

**Comment by foxbunny** [comment]
@syedkarim did you wait for the LED to turn off and then _remove_ the USB stick?

**Comment by foxbunny** [comment]
Apparently user error in combination with problems that will be addressed by other issues. Closing for now.
