### ISSUE TITLE
Add L-Band DIY receiver manual to the image

### ISSUE THREAD

**Issue by rachelgrace** [Outernet-Project/rxOS#166]
Add PDF to the image so it is available under a top level folder called Outernet Manual. Current version available, revisions coming on 9/22/16: https://drive.google.com/a/outernet.is/file/d/0B2KxJTU-t37gam1pZUpCR0NMc0U/view?usp=sharing

**Comment by cyoung** [comment]
Which image? I've done the CHIP programming procedure with the latest and the manual is the top level directory.

**Comment by syedkarim** [comment]
Yes, the manual was included in the last release.
