### ISSUE TITLE
Add multifs support

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/rxOS#170]
0. mount internal storage to /mnt/internal
1. bind mount /mnt/internal to /mnt/external at boot - fstab
2. multifs /mnt/external,/mnt/internal to /mnt/downloads - fstab
3. point fsal always at /mnt/downloads - NOT at /mnt/internal and/or /mnt/external - fsal config, hotplug
4. in hotplug script, mount the device fs using mount -o nonempty to /mnt/external; then issue fsal_refresh - hotplug. 
5. on device remove, just unmount by device path, not by /mnt/external
6. fix lighty to not merge two dirs - lighty.
7. LRU - 
8. Hotplug
9. ftp
10. File "moving" feature in diskspace component gets disabled.

**Comment by foxbunny** [comment]
Note regarding umounting (item No.6), the umount command cannot umount a device on hotplug event, since the event fires _after_ the device had been removed. This means that the umount must be preformed on the mount point. If needed, the internal storage should be rebound to the external storage mount point after unmounting.

**Comment by abgoyal** [comment]
implemented.
