### ISSUE TITLE
Update documentation to use different URL other than http://outernet.is for Librarian access

### ISSUE THREAD

**Issue by cyoung** [Outernet-Project/rxOS#180]
[This manual](https://static1.squarespace.com/static/55ccfcb0e4b0c5b275895965/t/57eabac7c534a59d49fe64c9/1475001037148/Outernet+L-Band+Manual+v02.02.pdf) instructs the new user to go to http://outernet.is after connecting to the "Outernet" network. `dnsmasq` appears to serve the A record `10.0.0.1` for all hostname A requests (except for `usb.rxos.com`).
There are a number of issues with this:

1. The "public internet" http://outerinet.is 301 (permanent) redirects to https://outernet.is. This can cause the user's browser (in my case, it did with Chrome running on iOS 10) to cache the http://outernet.is -> https://outernet.is redirect. HTTPS is not running on rxOS, so this caused connectivity problems for me. 
2. There are URL redirects like "http://outernet.is/en/files/" which don't exist on the actual public internet website.
3. There are URLs on the public internet site that Librarian doesn't serve. Causes confusion when tabs are left open and the browser attempts a refresh on the URL.

**Suggest changing http://outernet.is URL in documentation to something else**. Currently I'm using http://10.0.0.1 and this seems to be the only reliable way for me to access Librarian on iOS.

**Comment by syedkarim** [comment]
Yes, this definitely needs to be updated. Can you try http://outernet

**Comment by cyoung** [comment]
Doesn't work for me in Chrome on macOS. Stuck on host resolution. Haven't looked into why yet.

**Comment by syedkarim** [comment]
How about http://my.outernet.is

**Comment by abgoyal** [comment]
http://my.outernet.is is the goto URL now for both AP mode as well as STA mode. In STA mode it will work if the telemetry reporting is working - though it might take a few minutes to kick-in after boot.
