### ISSUE TITLE
Version mismatch on telemetry_client installed with latest rxOS RPi image

### ISSUE THREAD

**Issue by cyoung** [Outernet-Project/rxOS#181]
[rxOS][root@rxos:/etc/init.d]# cat /usr/bin/telemetry_client
     #!/usr/bin/python
     # EASY-INSTALL-ENTRY-SCRIPT: 'telemetry-client==0.9','console_scripts','telemetry_client'
     __requires__ = 'telemetry-client==0.9'
     import sys
     from pkg_resources import load_entry_point
     
     if __name__ == '__main__':
         sys.exit(
             load_entry_point('telemetry-client==0.9', 'console_scripts', 'telemetry_client')()
         )
It appears the changes from `v0.9` to `v1.0` have been applied, however.

**Comment by abgoyal** [comment]
fixed

**Comment by cyoung** [comment]
Ref: https://github.com/Outernet-Project/telemetry_client/commit/2d03d3728a0005131f38dbec8edbfe4d1b6f5c85, thanks.
