### ISSUE TITLE
Method for setting real time clock in rxOS?

### ISSUE THREAD

**Issue by cyoung** [Outernet-Project/rxOS#182]
Is sending the time via the satellite transmissions periodically an option?

I note in `/var/log/messages`:

    Jan  1 00:00:16 rxos daemon.err lighttpd[378]: (server.c.1053) WARNING: unknown config-key: server.accesslog-filename (ignored) 
    Jan  1 00:00:16 rxos auth.notice su: + /dev/console root:postgres
    Jan  1 00:00:17 rxos daemon.err ntpd[370]: bind(24) AF_INET6 fe80::ba27:ebff:febe:33dc%3#123 flags 0x11 failed: Cannot assign requested address
    Jan  1 00:00:17 rxos daemon.err ntpd[370]: unable to create socket on wlan0 (6) for fe80::ba27:ebff:febe:33dc%3#123
    Jan  1 00:00:17 rxos daemon.info ntpd[370]: failed to init interface for address fe80::ba27:ebff:febe:33dc%3
    Oct  9 05:19:18 rxos daemon.info dnsmasq[397]: started, version 2.75 cachesize 150
    Oct  9 05:19:18 rxos daemon.info dnsmasq[397]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua no-TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
    Oct  9 05:19:18 rxos daemon.info dnsmasq[397]: cleared cache
    Oct  9 05:19:18 rxos user.notice cleanup: Needs 204800 KiB, but there is already 11703488 KiB, nothing to do
    Oct  9 05:19:18 rxos user.err ondd: [main] Unable to load config: /mnt/data/ondd.conf (null)

The system clock will never be correct unless you have an outside clock source. CHIP doesn't appear to have an RTC so this applies both to RPi and CHIP.

Not sure if any of the content management functions use dates, but perhaps some of the services that rxOS uses (dns lease management, etc) may depend on the system clock to some extent.

**Comment by abgoyal** [comment]
yes, rxos has satellite time updates.
