### ISSUE TITLE
Basic spectrum plot sweep and display

### ISSUE THREAD

**Issue by zodoczi** [Outernet-Project/rxOS#184]
possibly using rtl-power tool: http://kmkeen.com/rtl-power/

in many cases there is no other way to "look from the CHIP+SDR point of view" what signal and noise it sees. 

+/- 0.1...2 MHz around the main Outernet signal frequency should be fine options.

**Comment by abgoyal** [comment]
it cannot be done. the I/Q data goes to sdr100. Also that kinda display over a web interface is not possible.
