### ISSUE TITLE
compiling openssl/pem.h missing

### ISSUE THREAD

**Issue by pcnate** [Outernet-Project/rxOS#185]
Following readme for compiling for CHIP and I get the following error about missing `openssl/pem.h`

    # CFLAGS are not relayed because LARGEFILE flags cause mkpkg and installer
    # to fail.
    PATH="/home/pcnate/github/rxOS/out/chip/host/bin:/home/pcnate/github/rxOS/out/chip/host/sbin:/home/pcnate/github/rxOS/out/chip/host/usr/bin:/home/pcnate/github/rxOS/out/chip/host/usr/sbin:/home/pcnate/bin:/home/pcnate/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/pcnate/.npm-global/bin:/home/pcnate/.npm-global/bin:/usr/share/atom/resources/app/apm/bin/apm" PKG_CONFIG="/home/pcnate/github/rxOS/out/chip/host/usr/bin/pkg-config" PKG_CONFIG_SYSROOT_DIR="/" PKG_CONFIG_LIBDIR="/home/pcnate/github/rxOS/out/chip/host/usr/lib/pkgconfig" /usr/bin/make -j9 CFLAGS= LDFLAGS="-L/home/pcnate/github/rxOS/out/chip/host/lib -L/home/pcnate/github/rxOS/out/chip/host/usr/lib -Wl,-rpath,/home/pcnate/github/rxOS/out/chip/host/usr/lib" CROSS_COMPILE=/home/pcnate/github/rxOS/out/chip/host/usr/bin/arm-buildroot-linux-gnueabihf- TARGET_LDFLAGS="" -C /home/pcnate/github/rxOS/out/chip/build/host-pkgtool-v0.5.0 clean mkpkg
    rm -f pkgtool mkpkg installer.bin installer.o
    /home/pcnate/github/rxOS/out/chip/host/usr/bin/arm-buildroot-linux-gnueabihf-gcc -Wall -DLINUX  -o installer.bin installer.cpp -static -lstdc++ -lcrypto
    installer.cpp: In function ‘int lookup_ubivol_id(const char*, int)’:
    installer.cpp:494:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
          if( ((len -1) == strlen(name)) && (0 == strncmp( buf, name, strlen(name) )))
                        ^
    /home/pcnate/github/rxOS/out/chip/host/usr/bin/arm-buildroot-linux-gnueabihf-strip installer.bin
    ld -r -b binary -o installer.o installer.bin
    gcc  -L/home/pcnate/github/rxOS/out/chip/host/lib -L/home/pcnate/github/rxOS/out/chip/host/usr/lib -Wl,-rpath,/home/pcnate/github/rxOS/out/chip/host/usr/lib -o mkpkg mkpkg.cpp installer.o -lstdc++ -lcrypto
    mkpkg.cpp:12:25: fatal error: openssl/pem.h: No such file or directory
    compilation terminated.
    Makefile:29: recipe for target 'mkpkg' failed
    make[3]: *** [mkpkg] Error 1
    package/pkg-generic.mk:195: recipe for target '/home/pcnate/github/rxOS/out/chip/build/host-pkgtool-v0.5.0/.stamp_built' failed
    make[2]: *** [/home/pcnate/github/rxOS/out/chip/build/host-pkgtool-v0.5.0/.stamp_built] Error 2
    Makefile:36: recipe for target '_all' failed
    make[1]: *** [_all] Error 2
    make[1]: Leaving directory '/home/pcnate/github/rxOS/buildroot'
    Makefile:107: recipe for target 'out/chip/.stamp_built' failed
    make: *** [out/chip/.stamp_built] Error 2

I have tried this on Debian 8 and Ubuntu 16.04.1 LTS. Both are fully up to date.

**Comment by abgoyal** [comment]
install libssl-dev

**Comment by pcnate** [comment]
I had tried this on Debian 8 and it did not work. I forgot about this on Ubuntu.
I am trying now on Ubuntu, seems to be working.
