### ISSUE TITLE
AP/wireless driver removed?

### ISSUE THREAD

**Issue by weirdal3333** [Outernet-Project/rxOS#187]
This I think doesn't let the C.H.I.P's wifi works properly...
Can you get it to compile with GCC 6.1 so it works?
You could also find another, compatible driver.

You removed this line:
`BR2_PACKAGE_MT7601APSTA=y`

It was removed in this commit:
https://github.com/Outernet-Project/rxOS/commit/1d6557ab1c40b651cbc4d893591b3a7aa4ea10d5

**Comment by abgoyal** [comment]
MT7601 is _NOT_ the chip wifi driver.
