### ISSUE TITLE
Git dependency fails to clone

### ISSUE THREAD

**Issue by Thempra** [Outernet-Project/rxOS#189]
It's not possible start to compile and contribute:

git clone --recursive https://github.com/Outernet-Project/rxOS.git -b develop
....
....
.....
fatal: reference is not a tree: 38ab46b9dfd7ff4691974b96c366cce220c8bf06
Unable to checkout «38ab46b9dfd7ff4691974b96c366cce220c8bf06» in submodule path «rxos/package»

**Comment by abgoyal** [comment]
fixed.
