### ISSUE TITLE
Sidebar auto-hides on video player

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/rxOS#96]
When a list of videos is viewed through Watch, and a new video is selected through the sidebar, the sidebar immediately hides itself. The user must then expand the playlist sidebar in order to select another video. 

![image](https://cloud.githubusercontent.com/assets/1186964/15840556/3a01394e-2c10-11e6-8d88-1ca79d1b2949.png)

![image](https://cloud.githubusercontent.com/assets/1186964/15840561/448b2b72-2c10-11e6-9dd8-8298dfafd599.png)

**Comment by foxbunny** [comment]
Wrong repo, closing.
